### ISSUE TITLE
Client not found Baikal resources

### ISSUE THREAD

**Issue by zcatav** [YunoHost-Apps/baikal_ynh#80]
Hi,
I'm trying to install Baikal to my new Yunohost instance.

### Describe the bug

On new installed and configured Baikal 0.9.3, Thunderbird 115.1.1 (64 bit)
app could not connect, showing the error "No calendar found at this location".
URI like this https://domain.ltd/baikal/dav.php and user and passwd correct.

### Context

- Hardware: *Raspberry Pi at home *
- YunoHost version: 11.2.3 stable
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *

### Expected behavior

*Thunderbird connects to Baikal seamlessly.*

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*
```
/var/log/nginx/domain.ltd-error.log
2023/08/25 13:10:58 [error] 58426#58426: *3889 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: domain.ltd, request: "PROPFIND /baikal/dav.php/calendars/user/default/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "domain.ltd"
2023/08/25 13:10:59 [error] 58425#58425: *3894 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: domain.ltd, request: "GET /baikal/dav.php/calendars/user/default/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "domain.ltd"
2023/08/25 13:10:59 [error] 58426#58426: *3895 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: domain.ltd, request: "PROPFIND /baikal/dav.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "domain.ltd"
2023/08/25 13:10:59 [error] 58426#58426: *3900 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: domain.ltd, request: "PROPFIND /baikal/dav.php/calendars/user/default/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "domain.ltd"
2023/08/25 13:11:00 [error] 58426#58426: *3904 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: domain.ltd, request: "PUT /baikal/dav.php/calendars/user/default/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "domain.ltd"
/var/log/nginx/devop.domain.ltd-access.log
12.12.12.12 - - [25/Aug/2023:14:36:53 +0300] "HEAD /dav.php HTTP/2.0" 401 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:36:54 +0300] "GET /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:36:54 +0300] "PROPFIND /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:36:54 +0300] "PROPFIND /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:11 +0300] "HEAD /dav.php HTTP/2.0" 401 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:37:11 +0300] "HEAD /dav.php HTTP/2.0" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:11 +0300] "PROPFIND /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:37:11 +0300] "PROPFIND /dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:11 +0300] "GET /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:37:11 +0300] "GET /dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:11 +0300] "PROPFIND /.well-known/caldav HTTP/2.0" 301 162 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:11 +0300] "PROPFIND /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:37:11 +0300] "PROPFIND /dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:12 +0300] "PROPFIND /dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:37:12 +0300] "PROPFIND /dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:12 +0300] "PROPFIND / HTTP/2.0" 405 150 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:37:12 +0300] "PUT /dav.php HTTP/2.0" 401 411 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:37:12 +0300] "PUT /dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:38:00 +0300] "GET /admin/?/logout/ HTTP/2.0" 302 0 "https://devop.domain.ltd/admin/?/users/new/1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:38:01 +0300] "GET /admin/ HTTP/2.0" 200 2325 "https://devop.domain.ltd/admin/?/users/new/1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
127.0.0.1 - - [25/Aug/2023:14:44:14 +0300] "GET /.well-known/caldav HTTP/2.0" 302 138 "-" "curl/7.74.0"
127.0.0.1 - - [25/Aug/2023:14:44:14 +0300] "GET /.well-known/carddav HTTP/2.0" 302 138 "-" "curl/7.74.0"
12.12.12.12 - user [25/Aug/2023:14:46:44 +0300] "GET /baikal/ HTTP/2.0" 200 2530 "https://domain.ltd/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:46:46 +0300] "GET /baikal/admin/ HTTP/2.0" 200 2339 "https://devop.domain.ltd/baikal/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:47:12 +0300] "POST /baikal/admin/ HTTP/2.0" 200 2533 "https://devop.domain.ltd/baikal/admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:47:19 +0300] "POST /baikal/admin/ HTTP/2.0" 302 0 "https://devop.domain.ltd/baikal/admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:47:19 +0300] "GET /baikal/admin/ HTTP/2.0" 200 5591 "https://devop.domain.ltd/baikal/admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:47:23 +0300] "GET /baikal/admin/?/users/ HTTP/2.0" 200 2804 "https://devop.domain.ltd/baikal/admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:47:25 +0300] "GET /baikal/admin/?/users/new/1/ HTTP/2.0" 200 5202 "https://devop.domain.ltd/baikal/admin/?/users/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:47:40 +0300] "POST /baikal/admin/?/users/new/1/ HTTP/2.0" 200 6745 "https://devop.domain.ltd/baikal/admin/?/users/new/1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - - [25/Aug/2023:14:48:04 +0300] "HEAD /baikal/dav.php HTTP/2.0" 401 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:04 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:05 +0300] "GET /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:05 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:18 +0300] "HEAD /baikal/dav.php HTTP/2.0" 401 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:18 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:48:18 +0300] "HEAD /baikal/dav.php HTTP/2.0" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:48:18 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:18 +0300] "PROPFIND /.well-known/caldav HTTP/2.0" 301 162 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:18 +0300] "GET /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:18 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:48:18 +0300] "GET /baikal/dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:48:18 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:19 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 401 402 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:19 +0300] "PROPFIND / HTTP/2.0" 302 138 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:48:19 +0300] "PROPFIND /baikal/dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - - [25/Aug/2023:14:48:19 +0300] "PUT /baikal/dav.php HTTP/2.0" 401 411 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:48:19 +0300] "PUT /baikal/dav.php HTTP/2.0" 500 312 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:115.0) Gecko/20100101 Thunderbird/115.1.1"
12.12.12.12 - user [25/Aug/2023:14:51:37 +0300] "GET /baikal/admin/ HTTP/2.0" 200 5591 "https://devop.domain.ltd/baikal/admin/?/users/new/1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
12.12.12.12 - user [25/Aug/2023:14:54:28 +0300] "GET /baikal/admin/?/users/ HTTP/2.0" 200 4148 "https://devop.domain.ltd/baikal/admin/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
/var/log/nginx/devop.domain.ltd-error.log
2023/08/25 14:48:18 [error] 99966#99966: *4292 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: devop.domain.ltd, request: "PROPFIND /baikal/dav.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "devop.domain.ltd"
2023/08/25 14:48:18 [error] 99966#99966: *4298 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: devop.domain.ltd, request: "GET /baikal/dav.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "devop.domain.ltd"
2023/08/25 14:48:18 [error] 99966#99966: *4297 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: devop.domain.ltd, request: "PROPFIND /baikal/dav.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "devop.domain.ltd"
2023/08/25 14:48:19 [error] 99966#99966: *4303 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: devop.domain.ltd, request: "PROPFIND /baikal/dav.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "devop.domain.ltd"
2023/08/25 14:48:19 [error] 99970#99970: *4309 FastCGI sent in stderr: "PHP message: ErrorException: Creation of dynamic property Baikal\Core\LDAPUserBindAuth::$currentUser is deprecated in /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php:67
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(67): Baikal\Framework::exception_error_handler()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(179): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(" while reading response header from upstream, client: 12.12.12.12, server: devop.domain.ltd, request: "PUT /baikal/dav.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "devop.domain.ltd"
```

Thanks for your attention.

**Comment by zcatav** [comment]
I've installed 0.9.2 and it works as expected.

**Comment by zcatav** [comment]
I've upgrade it again and after the upgrade, logging into the baikal administrator account and re-activating it. Now it works.
